### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by Paulijuz** [Th3o4oR/ov-stengt-inator#3]
Add a config file for easy project configuration. I would prefer either YAML or TOML. 

Things that should be in the config:
- [ ] Wifi SSID with optional password and/or login request
- [ ] Color configuration for different statuses
- [ ] Blink frequency
- [ ] Ping URL

**Comment by Th3o4oR** [comment]
[√] Done
[√] Done
[√] Done
[√] Done
